// Complete CDMX Spots Data
// Compiled from Bob's 10 years of CDMX experience + research Feb 14-15, 2026

const allSpots = [
    // ========== JAPANESE ==========
    {
        name: 'Taishu Teppan Sango',
        category: 'japanese',
        type: 'Teppanyaki',
        description: 'Okonomiyaki, teppanyaki, izakaya. Small spot, gets busy.',
        address: 'Río Pánuco 128, Col. Cuauhtémoc',
        distance: '10 min walk from Sheraton',
        hours: 'Tue-Sun 1pm-10pm, Closed Mon',
        phone: '',
        price: '~1,800 MXN for 2 people',
        google_maps: 'https://maps.google.com/?q=Taishu+Teppan+Sango+Mexico+City',
        bob_intel: 'Bob tried to go 2/14/26 but it was full. Backup = WANWAN Sakaba.'
    },
    {
        name: 'WANWAN Sakaba',
        category: 'japanese',
        type: 'Izakaya',
        description: 'Traditional izakaya with ramen and fried dishes.',
        address: 'Londres 209, Juárez',
        distance: '8 min walk from Sheraton',
        hours: 'Mon-Sat 1pm-11pm, Sun 1pm-9pm',
        phone: '',
        price: '~1,800 MXN for 2 people',
        google_maps: 'https://maps.google.com/?q=WANWAN+Sakaba+Londres+209+Juarez+Mexico+City',
        bob_intel: 'Bob went here 2/14/26 when Sango was full. Had sushi + ramen, 1,795 MXN total. Good backup option.'
    },
    {
        name: 'Kura Izakaya',
        category: 'japanese',
        type: 'Izakaya',
        description: 'Japanese-run izakaya. Pork belly, premium sashimi, full menu.',
        address: 'Colima 378, Roma Norte',
        distance: '15 min walk from Sheraton',
        hours: 'Mon-Sat 1pm-11pm, Sun 1pm-6pm',
        phone: '',
        price: '400-600 MXN',
        google_maps: 'https://maps.google.com/?q=Kura+Izakaya+Colima+378+Roma+Norte+Mexico+City',
        bob_intel: ''
    },
    {
        name: 'Rokai',
        category: 'japanese',
        type: 'Ramen',
        description: 'Top ramen spot. Tonkotsu, miso, shoyu. Gyoza, karaage.',
        address: 'Medellín 101, Roma Norte',
        distance: '15 min walk from Sheraton',
        hours: 'Mon-Sat 1pm-10pm, Sun 1pm-9pm',
        phone: '',
        price: '200-350 MXN',
        google_maps: 'https://maps.google.com/?q=Rokai+Medellin+101+Roma+Norte+Mexico+City',
        bob_intel: ''
    },
    {
        name: 'Kioko',
        category: 'japanese',
        type: 'Japanese',
        description: 'Upscale spot. Wagyu, sashimi, omakase. Great for date night.',
        address: 'Michoacán 25, Condesa',
        distance: '20 min walk from Sheraton',
        hours: 'Tue-Sat 2pm-11pm, Sun 2pm-10pm',
        phone: '',
        price: '800-1,200 MXN',
        google_maps: 'https://maps.google.com/?q=Kioko+Michoacan+25+Condesa+Mexico+City',
        bob_intel: ''
    },
    {
        name: 'C.O.M.E',
        category: 'japanese',
        type: 'Yakitori',
        description: 'Budget yakitori, udon, mochi. Lunch specials ~90 MXN.',
        address: 'Coahuila 143, Roma Sur',
        distance: '15 min walk from Sheraton',
        hours: 'Mon-Sat 12pm-9pm, Closed Sun',
        phone: '',
        price: '90-200 MXN',
        google_maps: 'https://maps.google.com/?q=COME+Coahuila+143+Roma+Sur+Mexico+City',
        bob_intel: ''
    },

    // ========== KOREAN ==========
    {
        name: 'Kpop BBQ',
        category: 'korean',
        type: 'Korean BBQ',
        description: 'All-you-can-eat KBBQ. Beef, pork, chicken. Banchan, soju.',
        address: 'Insurgentes Sur 349, Hipódromo',
        distance: '20 min walk / 8 min Uber',
        hours: 'Mon-Sun 1pm-11pm',
        phone: '+52 55 5264 8905',
        price: '350-450 MXN AYCE',
        google_maps: 'https://maps.google.com/?q=Kpop+BBQ+Insurgentes+Sur+349+Hipodromo+Mexico+City',
        bob_intel: ''
    },
    {
        name: 'Seoul Town',
        category: 'korean',
        type: 'Korean BBQ',
        description: 'Authentic KBBQ, banchan station, private booths.',
        address: 'Dinamarca 106, Juárez',
        distance: '15 min walk from Sheraton',
        hours: 'Mon-Sun 1pm-11pm',
        phone: '+52 55 5525 0022',
        price: '400-600 MXN',
        google_maps: 'https://maps.google.com/?q=Seoul+Town+Dinamarca+106+Juarez+Mexico+City',
        bob_intel: ''
    },
    {
        name: 'Gogiyo',
        category: 'korean',
        type: 'Korean BBQ',
        description: 'Korean-run spot. Premium cuts, kimchi pancake, bibimbap.',
        address: 'Amsterdam 246, Hipódromo Condesa',
        distance: '25 min walk / 10 min Uber',
        hours: 'Tue-Sun 2pm-11pm, Closed Mon',
        phone: '',
        price: '500-700 MXN',
        google_maps: 'https://maps.google.com/?q=Gogiyo+Amsterdam+246+Hipodromo+Condesa+Mexico+City',
        bob_intel: ''
    },
    {
        name: 'Mukbang Korean Restaurant',
        category: 'korean',
        type: 'Korean',
        description: 'Full Korean menu. Bulgogi, jjigae, tteokbokki.',
        address: 'Tlaxcala 173, Hipódromo',
        distance: '20 min walk / 8 min Uber',
        hours: 'Tue-Sun 1pm-10pm, Closed Mon',
        phone: '',
        price: '200-400 MXN',
        google_maps: 'https://maps.google.com/?q=Mukbang+Tlaxcala+173+Hipodromo+Mexico+City',
        bob_intel: ''
    },
    {
        name: 'Hanu Korean Restaurant',
        category: 'korean',
        type: 'Korean',
        description: 'Casual Korean spot. Gimbap, ramyeon, fried chicken.',
        address: 'Jalapa 97, Roma Norte',
        distance: '18 min walk from Sheraton',
        hours: 'Wed-Mon 2pm-10pm, Closed Tue',
        phone: '',
        price: '150-300 MXN',
        google_maps: 'https://maps.google.com/?q=Hanu+Jalapa+97+Roma+Norte+Mexico+City',
        bob_intel: ''
    },

    // ========== ROCK BARS / NIGHTLIFE ==========
    {
        name: 'Cueva de Lobos',
        category: 'nightlife',
        type: 'Rock Bar',
        description: 'Rock bar with live bands, signature cocktails (Lobo Especial).',
        address: 'C. Génova 30, Juárez',
        distance: '5 min walk from Sheraton',
        hours: 'Mon-Wed & Sun 10am-2am, Thu-Sat 8am-2am',
        phone: '+52 55 5507 2186',
        price: '150-250 MXN drinks',
        google_maps: 'https://maps.google.com/?q=Cueva+de+Lobos+Genova+30+Juarez+Mexico+City',
        bob_intel: 'Bob\'s #1 rock bar. End an epic day here OR go to Queen\'s. Your call.'
    },
    {
        name: 'Pulquería Los Insurgentes',
        category: 'nightlife',
        type: 'Pulquería',
        description: '4-story pulque bar with rooftop terrace, DJs, dance floor. Great for first-time pulque.',
        address: 'Av. Insurgentes Sur 226, Roma Norte',
        distance: '10 min Uber from Sheraton',
        hours: 'Fri 9am-11pm, Sat-Sun 9am-6pm (late nights vary)',
        phone: '+52 55 5207 0917',
        price: '60-120 MXN pulque',
        google_maps: 'https://maps.google.com/?q=Pulqueria+Los+Insurgentes+Mexico+City',
        bob_intel: 'Cool spot for first-time pulque. Poppin on weekends, chill on weekdays.'
    },
    {
        name: 'Jazzatlán Capital',
        category: 'nightlife',
        type: 'Jazz Bar',
        description: 'Live jazz and flamenco. Intimate, date-night vibe.',
        address: 'Zona Rosa',
        distance: '8 min walk from Sheraton',
        hours: 'Wed-Sat 8pm-2am',
        phone: '',
        price: '200-400 MXN',
        google_maps: 'https://maps.google.com/?q=Jazzatlan+Capital+Zona+Rosa+Mexico+City',
        bob_intel: ''
    },
    {
        name: 'Multiforo Alicia',
        category: 'nightlife',
        type: 'Underground Venue',
        description: 'Underground punk, metal, indie shows. Dive bar aesthetic.',
        address: 'Cuauhtémoc 91-A, Centro',
        distance: '15 min Uber',
        hours: 'Event-based (Thu-Sat usually)',
        phone: '+52 55 5510 2164',
        price: '100-300 MXN cover',
        google_maps: 'https://maps.google.com/?q=Multiforo+Alicia+Centro+Mexico+City',
        bob_intel: ''
    },
    {
        name: 'La Perla',
        category: 'nightlife',
        type: 'Dive Bar',
        description: 'Old-school cantina. Live mariachi, norteño, rock. Cash only.',
        address: 'República de Cuba 44, Centro',
        distance: '15 min Uber',
        hours: 'Mon-Sat 1pm-1am, Closed Sun',
        phone: '',
        price: '80-150 MXN drinks',
        google_maps: 'https://maps.google.com/?q=La+Perla+Republica+de+Cuba+44+Centro+Mexico+City',
        bob_intel: ''
    },
    {
        name: 'Vaquita Bar',
        category: 'nightlife',
        type: 'Dance Club',
        description: 'Party club. Open bar packages, DJ, dance floor.',
        address: 'Insurgentes Sur, Zona Rosa',
        distance: '10 min walk from Sheraton',
        hours: 'Thu-Sat 10pm-4am',
        phone: '',
        price: '400-600 MXN open bar',
        google_maps: 'https://maps.google.com/?q=Vaquita+Bar+Zona+Rosa+Mexico+City',
        bob_intel: ''
    },

    // ========== STRIP CLUBS (ADULT 18+) ==========
    {
        name: 'Queen\'s',
        category: 'adult',
        type: 'Strip Club',
        description: 'Upscale strip club. VIP sections, bottle service.',
        address: 'Hamburgo, Juárez',
        distance: '12 min walk from Sheraton',
        hours: 'Mon-Sat 9pm-4am',
        phone: '',
        price: '500-1,500 MXN entry + drinks',
        google_maps: 'https://maps.google.com/?q=Queens+Hamburgo+Juarez+Mexico+City',
        bob_intel: 'Bob\'s pick for strip clubs. Can be the finale of an epic Teotihuacan → Xochimilco → Mariachi day.'
    },
    {
        name: 'Cabaret Show Girls',
        category: 'adult',
        type: 'Strip Club',
        description: 'Multi-level club, private rooms, full bar.',
        address: 'Londres, Juárez',
        distance: '10 min walk from Sheraton',
        hours: 'Mon-Sat 8pm-4am',
        phone: '',
        price: '400-1,000 MXN',
        google_maps: 'https://maps.google.com/?q=Cabaret+Show+Girls+Londres+Juarez+Mexico+City',
        bob_intel: ''
    },
    {
        name: 'Las Adelitas',
        category: 'adult',
        type: 'Strip Club',
        description: 'Mid-tier, more relaxed vibe than upscale spots.',
        address: 'Insurgentes Sur',
        distance: '15 min Uber',
        hours: 'Daily 6pm-3am',
        phone: '',
        price: '300-700 MXN',
        google_maps: 'https://maps.google.com/?q=Las+Adelitas+Insurgentes+Sur+Mexico+City',
        bob_intel: ''
    },
    {
        name: 'Bar Oriente',
        category: 'adult',
        type: 'Strip Club',
        description: 'Budget option. More dive bar than club.',
        address: 'Centro',
        distance: '15 min Uber',
        hours: 'Daily 4pm-2am',
        phone: '',
        price: '150-400 MXN',
        google_maps: '',
        bob_intel: 'Seedy tier. Not for everyone.'
    },

    // ========== BOB'S 5-DAY ITINERARY SPOTS ==========
    {
        name: 'Madre Café',
        category: 'breakfast',
        type: 'Breakfast/Brunch',
        description: 'Cozy breakfast spot, great coffee, pastries.',
        address: 'Roma Norte',
        distance: '',
        hours: 'Mon-Sun 8am-5pm',
        phone: '',
        price: '150-250 MXN',
        google_maps: '',
        bob_intel: 'Part of Bob\'s 5-day itinerary.'
    },
    {
        name: 'Máximo Bistrot',
        category: 'mexican',
        type: 'Fine Dining',
        description: 'Upscale contemporary Mexican cuisine.',
        address: 'Álvaro Obregón 65 Bis, Roma Norte',
        distance: '',
        hours: 'Mon-Sat 1pm-11pm, Closed Sun',
        phone: '',
        price: '800-1,500 MXN',
        google_maps: 'https://maps.google.com/?q=Maximo+Bistrot+Alvaro+Obregon+65+Bis+Roma+Norte+Mexico+City',
        bob_intel: 'Part of Bob\'s 5-day itinerary. High-end dinner spot.'
    },
    {
        name: 'La Docena',
        category: 'mexican',
        type: 'Oyster Bar',
        description: 'Fresh oysters, seafood cocktails, beachside vibe.',
        address: 'Álvaro Obregón 31, Roma Norte',
        distance: '',
        hours: 'Daily 12pm-midnight',
        phone: '',
        price: '400-800 MXN',
        google_maps: 'https://maps.google.com/?q=La+Docena+Alvaro+Obregon+31+Roma+Norte+Mexico+City',
        bob_intel: 'Part of Bob\'s 5-day itinerary. Great for lunch/happy hour.'
    },
    {
        name: 'Limosneros',
        category: 'mexican',
        type: 'Contemporary Mexican',
        description: 'Creative Mexican dishes, historic Centro location.',
        address: 'Ignacio Allende 3, Centro Histórico',
        distance: '',
        hours: 'Tue-Sat 1pm-11pm, Sun 1pm-6pm',
        phone: '',
        price: '500-900 MXN',
        google_maps: 'https://maps.google.com/?q=Limosneros+Ignacio+Allende+3+Centro+Historico+Mexico+City',
        bob_intel: 'Part of Bob\'s 5-day itinerary.'
    },
    {
        name: 'La Gruta',
        category: 'mexican',
        type: 'Cave Restaurant',
        description: 'Cave restaurant near Teotihuacan pyramids. Traditional Mexican food.',
        address: 'Near Teotihuacan',
        distance: '1 hour from CDMX',
        hours: 'Daily 8am-7pm',
        phone: '',
        price: '300-600 MXN',
        google_maps: 'https://maps.google.com/?q=La+Gruta+Teotihuacan+Mexico',
        bob_intel: 'Part of Bob\'s 5-day itinerary. Stop here after visiting the pyramids.'
    },
    {
        name: 'La Ciudadela Market',
        category: 'tourist',
        type: 'Artisan Market',
        description: 'Massive artisan market. Textiles, pottery, leather, souvenirs.',
        address: 'Balderas, Centro',
        distance: '15 min Uber',
        hours: 'Daily 9am-7pm',
        phone: '',
        price: 'Varies (haggle)',
        google_maps: 'https://maps.google.com/?q=La+Ciudadela+Market+Mexico+City',
        bob_intel: 'Part of Bob\'s 5-day itinerary. Best market for souvenirs.'
    },
    {
        name: 'La Merced Market',
        category: 'tourist',
        type: 'Food Market',
        description: 'Enormous food market. Fresh produce, spices, street food.',
        address: 'Anillo de Circunvalación, Centro',
        distance: '20 min Uber',
        hours: 'Daily 6am-6pm',
        phone: '',
        price: 'Budget-friendly',
        google_maps: 'https://maps.google.com/?q=La+Merced+Market+Mexico+City',
        bob_intel: 'Part of Bob\'s 5-day itinerary. Locals\' market, bring cash.'
    },
    {
        name: 'Arena México',
        category: 'tourist',
        type: 'Lucha Libre',
        description: 'Iconic wrestling arena. Friday night matches, masks, Dos Equis.',
        address: '189 Calle Dr. Lavista, Doctores',
        distance: '15 min Uber',
        hours: 'Shows Fridays 8:30pm',
        phone: '',
        price: '100-400 MXN tickets',
        google_maps: 'https://maps.google.com/?q=Arena+Mexico+189+Calle+Dr+Lavista+Doctores+Mexico+City',
        bob_intel: 'Part of Bob\'s 5-day itinerary. Get ringside seats, buy a mask.'
    },

    // ========== TOURIST / DAY TRIPS ==========
    {
        name: 'Xochimilco Canals',
        category: 'tourist',
        type: 'Boat Ride',
        description: 'Colorful trajinera boats. Bring drinks, speaker, snacks. Mariachi boats (avoid or embrace).',
        address: 'Embarcadero Nativitas or Embarcadero Fernando Celada',
        distance: '1 hour from Centro',
        hours: 'Daily 9am-6pm',
        phone: '',
        price: '500-800 MXN per boat (holds 10-15 people)',
        google_maps: 'https://maps.google.com/?q=Xochimilco+Nativitas+Embarcadero+Mexico+City',
        bob_intel: 'Bring your own drinks/speaker. Phone flashlight in bottle = instant ambience. Mariachi boats will hound you — negotiate or say no.'
    },
    {
        name: 'Teotihuacan Pyramids',
        category: 'tourist',
        type: 'Archaeological Site',
        description: 'Ancient pyramids. Climb Pyramid of the Sun. Get there early (opens 9am).',
        address: 'San Juan Teotihuacán, Estado de México',
        distance: '1 hour from Centro',
        hours: 'Daily 9am-5pm',
        phone: '',
        price: '80 MXN entry',
        google_maps: 'https://maps.google.com/?q=Teotihuacan+Pyramids+Mexico',
        bob_intel: 'Best option: ask Sheraton concierge for English-speaking private tour guide. Better than online tours. Go early, avoid noon heat. Lunch at La Gruta after.'
    },
    {
        name: 'Plaza Garibaldi',
        category: 'tourist',
        type: 'Mariachi Square',
        description: 'Mariachi central. Live music, tequila bars, pulquerías. Gets rowdy at night.',
        address: 'Plaza Garibaldi, Centro',
        distance: '15 min Uber',
        hours: 'Best after 8pm',
        phone: '',
        price: '100-200 MXN per mariachi song',
        google_maps: 'https://maps.google.com/?q=Plaza+Garibaldi+Mexico+City',
        bob_intel: 'Can be the end of an epic day: Teotihuacan → lunch → Xochimilco → mariachi square → Queen\'s OR Cueva de Lobos. Bring cash, negotiate mariachi prices.'
    },

    // ========== STREET VENDORS ==========
    {
        name: 'Tacos Don Güero',
        category: 'street',
        type: 'Tacos',
        description: '24-hour taco stand. Al pastor, asada, suadero.',
        address: 'Various locations (mobile stands)',
        distance: '',
        hours: '24 hours',
        phone: '',
        price: '15-25 MXN per taco',
        google_maps: '',
        bob_intel: 'Street tacos = safe if cooked fresh + lots of customers. Avoid stands with no line.'
    },
    {
        name: 'El Califa',
        category: 'street',
        type: 'Tacos',
        description: 'Famous taco chain. Gaonera, costilla, campechano.',
        address: 'Multiple locations (Zona Rosa, Condesa)',
        distance: '',
        hours: 'Til 4:30am',
        phone: '',
        price: '40-60 MXN per taco',
        google_maps: 'https://maps.google.com/?q=El+Califa+Zona+Rosa+Mexico+City',
        bob_intel: 'Open late, touristy but solid quality.'
    },
    {
        name: 'Elotes & Esquites Vendors',
        category: 'street',
        type: 'Corn',
        description: 'Grilled corn (elotes) or corn in a cup (esquites). Mayo, cheese, chili, lime.',
        address: 'Everywhere (parks, plazas, street corners)',
        distance: '',
        hours: 'Afternoons/evenings',
        phone: '',
        price: '30-50 MXN',
        google_maps: '',
        bob_intel: 'Super safe. Cooked in front of you. Skip if corn looks old/dry.'
    },
    {
        name: 'Tamales Vendors',
        category: 'street',
        type: 'Tamales',
        description: 'Morning vendors with steaming carts. Rajas, mole, dulce.',
        address: 'Metro stations, plazas (mornings)',
        distance: '',
        hours: '6am-11am',
        phone: '',
        price: '15-30 MXN per tamale',
        google_maps: '',
        bob_intel: 'Breakfast staple. Safe if steaming hot.'
    },
    {
        name: 'Churros Vendors',
        category: 'street',
        type: 'Dessert',
        description: 'Fresh churros with chocolate or cajeta.',
        address: 'Parks, plazas, near churches',
        distance: '',
        hours: 'Afternoons/evenings',
        phone: '',
        price: '20-40 MXN',
        google_maps: '',
        bob_intel: 'Best after dinner. Crispy outside, soft inside.'
    },

    // ========== WEED ZONES (ADULT 18+) ==========
    {
        name: 'Parque México',
        category: 'adult',
        type: 'Weed Zone',
        description: 'Condesa park. Chill vibe, people smoke openly. Cops don\'t care.',
        address: 'Av. México, Condesa',
        distance: '20 min walk / 10 min Uber',
        hours: 'All day',
        phone: '',
        price: '',
        google_maps: 'https://maps.google.com/?q=Parque+Mexico+Condesa+Mexico+City',
        bob_intel: 'Most tolerant spot. Bring your own.'
    },
    {
        name: 'Zona Rosa',
        category: 'adult',
        type: 'Weed Zone',
        description: 'Gay district. Bars, clubs. People smoke on patios.',
        address: 'Zona Rosa',
        distance: '5 min walk from Sheraton',
        hours: '',
        phone: '',
        price: '',
        google_maps: '',
        bob_intel: 'Pretty chill. Stay on main streets at night.'
    },
    {
        name: 'Roma Norte Side Streets',
        category: 'adult',
        type: 'Weed Zone',
        description: 'Bohemian neighborhood. People smoke on bar patios, side streets.',
        address: 'Roma Norte',
        distance: '15 min walk / 10 min Uber',
        hours: '',
        phone: '',
        price: '',
        google_maps: '',
        bob_intel: 'Laid-back area. Just be discreet.'
    },

    // ========== PHARMACIES ==========
    {
        name: 'Farmacias Similares',
        category: 'tourist',
        type: 'Pharmacy',
        description: 'Budget pharmacy chain. OTC meds, some antibiotics/ED pills without prescription.',
        address: 'Everywhere (red/yellow signs)',
        distance: '',
        hours: 'Many 24hr',
        phone: '',
        price: 'Cheap',
        google_maps: '',
        bob_intel: 'Azithromycin, Ciprofloxacin available OTC. ED pills too. Still illegal to import to US.'
    },
    {
        name: 'Farmacias del Ahorro',
        category: 'tourist',
        type: 'Pharmacy',
        description: 'Another big chain. Similar selection to Similares.',
        address: 'Everywhere (green signs)',
        distance: '',
        hours: 'Many 24hr',
        phone: '',
        price: 'Cheap',
        google_maps: '',
        bob_intel: ''
    },

    // ========== LATE-NIGHT / SEEDY BARS ==========
    {
        name: 'Café El Popular',
        category: 'nightlife',
        type: 'Late-Night Diner',
        description: '24/7 diner serving full meals + drinks. Cash only, unpretentious. Perfect for after-hours.',
        address: 'Centro Histórico',
        distance: '15 min Uber',
        hours: '24 hours',
        phone: '',
        price: '100-200 MXN',
        google_maps: 'https://maps.google.com/?q=Cafe+El+Popular+Centro+Historico+Mexico+City',
        bob_intel: 'Cash only. Classic late-night spot when everything else closes.'
    },
    {
        name: 'Hanky Panky',
        category: 'nightlife',
        type: 'Speakeasy',
        description: 'Hidden speakeasy. Nervous door approach, cocktails til sunrise.',
        address: 'Turín 40, Juárez',
        distance: '10 min walk from Sheraton',
        hours: 'Mon-Sat 7pm-2am',
        phone: '',
        price: '200-400 MXN cocktails',
        google_maps: 'https://maps.google.com/?q=Hanky+Panky+Turin+40+Juarez+Mexico+City',
        bob_intel: ''
    },
    {
        name: 'Centro de Salud',
        category: 'nightlife',
        type: 'Dive Bar',
        description: 'Grungy rock/metal/alt venue. Berlin vibes, local scene.',
        address: 'Centro Histórico',
        distance: '15 min Uber',
        hours: 'Thu-Sat 9pm-3am',
        phone: '',
        price: '100-250 MXN',
        google_maps: 'https://maps.google.com/?q=Centro+de+Salud+bar+Mexico+City',
        bob_intel: ''
    },
    {
        name: 'Zinco Jazz Club',
        category: 'nightlife',
        type: 'Jazz Club',
        description: '1930s bank vault converted to jazz club. Retro vibe, cocktails, food.',
        address: 'Motolinía 20, Centro Histórico',
        distance: '15 min Uber',
        hours: 'Wed-Sat 9pm-2am',
        phone: '',
        price: '300-500 MXN',
        google_maps: 'https://maps.google.com/?q=Zinco+Jazz+Club+Motolinia+Centro+Mexico+City',
        bob_intel: ''
    },
    {
        name: 'Cantina La No. 20',
        category: 'nightlife',
        type: 'Cantina',
        description: 'Traditional cantina across from Sheraton. Late-night tacos, tequila.',
        address: 'Near Paseo de la Reforma',
        distance: '4 min walk from Sheraton',
        hours: 'Late night',
        phone: '',
        price: '80-150 MXN',
        google_maps: '',
        bob_intel: 'Right across the street from Sheraton. Classic spot.'
    },

    // ========== XOCHIMILCO (2ND EMBARCADERO) ==========
    {
        name: 'Embarcadero Cuemanco',
        category: 'tourist',
        type: 'Boat Launch',
        description: 'Quieter, more ecological Xochimilco embarcadero. Deeper canals, less touristy.',
        address: 'Periférico Sur Adolfo Ruíz Cortines, Xochimilco, 16034 CDMX',
        distance: '1 hour from Centro',
        hours: 'Daily 8am-8pm',
        phone: '',
        price: '500-800 MXN per boat',
        google_maps: 'https://maps.google.com/?q=Embarcadero+Cuemanco+Xochimilco+CDMX',
        bob_intel: 'More nature-focused, less party vibe than Nativitas.'
    }
];

export default allSpots;
